// Icon names selectable in the content editor (rendered by components/site/content-icon.tsx).
export const ICON_OPTIONS: { value: string; label: string }[] = [
  { value: "droplets", label: "Su damlaları" },
  { value: "flask", label: "Laboratuvar şişesi" },
  { value: "utensils", label: "Çatal bıçak" },
  { value: "pill", label: "İlaç" },
  { value: "scroll", label: "Kâğıt rulo" },
  { value: "shirt", label: "Tekstil" },
  { value: "flame", label: "Alev" },
  { value: "zap", label: "Enerji" },
  { value: "ship", label: "Gemi" },
  { value: "wheat", label: "Başak" },
  { value: "factory", label: "Fabrika" },
  { value: "wrench", label: "Anahtar" },
  { value: "disc", label: "Disk" },
  { value: "ruler", label: "Cetvel" },
  { value: "map-pin", label: "Konum" },
  { value: "package", label: "Paket" },
  { value: "compass", label: "Pusula" },
  { value: "microscope", label: "Mikroskop" },
  { value: "timer", label: "Kronometre" },
  { value: "shield", label: "Kalkan" },
  { value: "handshake", label: "El sıkışma" },
  { value: "file-search", label: "Belge arama" },
  { value: "clock", label: "Saat" },
  { value: "truck", label: "Kamyon" },
  { value: "gauge", label: "Gösterge" },
  { value: "thermometer", label: "Termometre" },
  { value: "settings", label: "Dişli" },
  { value: "badge-check", label: "Onay rozeti" },
];
