// src/data/catalog.mjs → supabase/seed.sql
//   node scripts/build-seed.mjs
import fs from "node:fs";
import path from "node:path";
import { categories, products } from "../src/data/catalog.mjs";

const root = path.resolve(import.meta.dirname, "..");

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replaceAll("'", "''")}'`);
const arr = (a) => `array[${(a ?? []).map(q).join(",")}]::text[]`;
const json = (o) => `${q(JSON.stringify(o ?? []))}::jsonb`;

export const slugify = (text) =>
  text
    .toLocaleLowerCase("tr")
    .replaceAll("ı", "i").replaceAll("ğ", "g").replaceAll("ü", "u").replaceAll("ş", "s").replaceAll("ö", "o").replaceAll("ç", "c")
    .normalize("NFKD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

const lines = [
  "-- Generated by scripts/build-seed.mjs from src/data/catalog.mjs — do not edit by hand.",
  "begin;",
  "",
  "-- Categories",
];

categories.forEach((c, i) => {
  lines.push(
    `insert into public.categories (slug, name, summary, description, illustration, sort_order) values (${q(c.slug)}, ${q(c.name)}, ${q(c.summary)}, ${q(c.description)}, ${q(c.illustration)}, ${i * 10}) on conflict (slug) do nothing;`,
  );
  c.children.forEach((ch, j) => {
    lines.push(
      `insert into public.categories (parent_id, slug, name, summary, description, illustration, sort_order) values ((select id from public.categories where slug = ${q(c.slug)}), ${q(ch.slug)}, ${q(ch.name)}, ${q(ch.summary)}, ${q(ch.description ?? null)}, ${q(ch.illustration)}, ${j * 10}) on conflict (slug) do nothing;`,
    );
  });
});

lines.push("", "-- Products");
const seen = new Set();
products.forEach((p, i) => {
  const slug = slugify(p.code);
  if (seen.has(slug)) throw new Error(`Duplicate product slug: ${slug}`);
  seen.add(slug);
  lines.push(
    `insert into public.products (category_id, slug, code, name, summary, description, specs, materials, features, applications, standards, equivalents, industries, illustration, is_featured, sort_order) values (` +
      [
        `(select id from public.categories where slug = ${q(p.category)})`,
        q(slug), q(p.code), q(p.name), q(p.summary), q(p.description),
        json(p.specs), json(p.materials), arr(p.features), arr(p.applications), arr(p.standards), arr(p.equivalents), arr(p.industries),
        q(p.illustration), p.is_featured ? "true" : "false", i * 10,
      ].join(", ") +
      `) on conflict (slug) do nothing;`,
  );
});

lines.push("", "commit;", "");
fs.writeFileSync(path.join(root, "supabase", "seed.sql"), lines.join("\n"));
console.log(`seed.sql → ${categories.length} top-level categories, ${products.length} products`);
